version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: go
      MYSQL_DATABASE: appdb
#      MYSQL_USER: root
#      MYSQL_PASSWORD: go

  backend:
    image: backend-image  # Use the name of the Docker image you just built
    ports:
      - "5000:5000"
    depends_on:
      - mysql
